// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package common

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigDsn   = "dsn"
	DestinationConfigKey   = "key"
	DestinationConfigTable = "table"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigDsn: {
			Default:     "",
			Description: "DSN is the connection string for the MySQL database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigKey: {
			Default:     "",
			Description: "Key is the primary key of the specified table.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigTable: {
			Default:     "",
			Description: "Table is used as the target table into which records are inserted.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
