// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package common

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigDisableCanalLogs = "disableCanalLogs"
	SourceConfigTables           = "tables"
	SourceConfigUrl              = "url"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigDisableCanalLogs: {
			Default:     "",
			Description: "DisableCanalLogs disables verbose logs.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		SourceConfigTables: {
			Default:     "",
			Description: "Tables represents the tables to read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigUrl: {
			Default:     "",
			Description: "URL is the connection string for the Mysql database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
